version: '3.8'


services:
  gs_mr_db:
    image: postgres:latest
    container_name: gs_mr_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: ${POSTGRES_DB}
    secrets:
      - db_password
    volumes:
      - gs_mr_db_data:/var/lib/postgresql/data
    networks:
      - gs_mr_net
  
  gs_mr_backend:
    build: 
      context: ./movie-rating-backend
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=${POSTGRES_URL}
      - SPRING_DATASOURCE_USER=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD_FILE=/run/secrets/db_password
    container_name: gs_mr_backend
    secrets:
      - db_password
    depends_on:
      - gs_mr_db
    networks:
      - gs_mr_net
  
  gs_mr_frontend:
    build:
      context: ./movie-rating-frontend
      dockerfile: Dockerfile
    container_name: gs_mr_frontend
    networks:
      - gs_mr_net

  mr_nginx:
    image: nginx:latest
    container_name: gs_mr_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/cert.pem:/etc/ssl/certs/cert.pem
      - ./certs/key.pem:/etc/ssl/certs/key.pem
    ports:
      - "443:443"
    depends_on:
      - gs_mr_frontend
      - gs_mr_backend
    networks:
      - gs_mr_net

volumes:
  gs_mr_db_data:

networks:
  gs_mr_net:
    driver: bridge

secrets:
  db_password:
    file: ./secrets/db_password